### ISSUE TITLE
[BUG] Plugin is not working, no settings available

### ISSUE THREAD

**Issue by Canna71** [vslinko/obsidian-outliner#346]
I have been trying this plugin (v2.3.0) since version 0.15.6 and now on 0.15.9 of Obsidian, with no results.
The plugin seem to enable and load (the backward compatibility warning is shown) but then no difference in list rendering, no hotkey is working and no Outliner section is shown in the settings.

In the console I can see the following:

```
VM222 plugin:obsidian-outliner:2536 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'unload')
    at ObsidianOutlinerPlugin.eval (plugin:obsidian-outliner:2536:28)
    at Generator.next (<anonymous>)
    at eval (plugin:obsidian-outliner:29:71)
    at new Promise (<anonymous>)
    at __awaiter (plugin:obsidian-outliner:25:12)
    at ObsidianOutlinerPlugin.onunload (plugin:obsidian-outliner:2534:16)
    at ObsidianOutlinerPlugin.e.unload (app.js:1:730909)
    at e.<anonymous> (app.js:1:1547941)
    at app.js:1:235078
    at Object.next `(app.js:1:235183)
```

This happens on both Mac OS X and Windows 10

**Comment by Canna71** [comment]
OK I solved by debugging. It looks like even if I had the "use legacy editor setting off", Obsidian was passing it true to the plug in.
![image](https://user-images.githubusercontent.com/5303303/183964915-f3f12d69-e9fd-45b3-817e-c4c52d389b6d.png)
I had to turn it on, then off again, relaunch, and now the plugin is loading correctly and the Settings are there!

**Comment by vslinko** [comment]
@Canna71 thank you for the feedback. should be fixed in https://github.com/vslinko/obsidian-outliner/releases/tag/2.3.2
